code_lang: sql
llm_suite_type: open_license

num_domains: 10
num_topics_per_domain: 10
num_complexity_levels: 4

llm_as_a_judge: true
syntax_validation: true
<<<<<<< HEAD
=======
semantic_validation: true
>>>>>>> 14c5a0ae2d27a27167af225a0a8cb615fdb77c28
