- model_name: gretelai/gpt-mixtral-8x-22b
  litellm_params:
    model: openai/gretelai/gpt-mixtral-8x-22b
    base_url: https://llmproxy.dev.gretel.cloud/v1/
    temperature: 0.9
    extra_headers:
      Authorization: os.environ/GRETEL_DEV_API_KEY
    max_tokens: 32768
    top_p: 1.0
  tags:
  - open_license
  - nl

- model_name: gretelai/gpt-codestral-mamba
  litellm_params:
    model: openai/gretelai/gpt-codestral-mamba
    base_url: https://llmproxy.dev.gretel.cloud/v1/
    temperature: 0.9
    extra_headers:
      Authorization: os.environ/GRETEL_DEV_API_KEY
  tags:
  - open_license
  - code

- model_name: gretelai/gpt-groq-llama-3-1-8b
  litellm_params:
    model: openai/gretelai/gpt-groq-llama-3-1-8b
    base_url: https://llmproxy.dev.gretel.cloud/v1/
    temperature: 0.6
    max_tokens: 1024
    top_p: 0.9
    extra_headers:
      Authorization: os.environ/GRETEL_DEV_API_KEY
  tags:
  - open_license
  - judge
