- model_name: gretelai/gpt-mixtral-8x-22b
  litellm_params:
    model: openai/gretelai/gpt-mixtral-8x-22b
    base_url: https://llmproxy.dev.gretel.cloud/v1/
    extra_headers:
      Authorization: os.environ/GRETEL_DEV_API_KEY
  tags:
  - open_license
  - nl
  - judge

- model_name: gretelai/gpt-codestral-mamba
  litellm_params:
    model: openai/gretelai/gpt-codestral-mamba
    base_url: https://llmproxy.dev.gretel.cloud/v1/
    extra_headers:
      Authorization: os.environ/GRETEL_DEV_API_KEY
  tags:
  - open_license
  - code

- model_name: gretelai/gpt-groq-llama-3-1-8b
  litellm_params:
    model: openai/gretelai/gpt-groq-llama-3-1-8b
    base_url: https://llmproxy.dev.gretel.cloud/v1/
    extra_headers:
      Authorization: os.environ/GRETEL_DEV_API_KEY
  tags:
  - open_license
  - judge

- model_name: gretelai-mistral-nemo-2407
  litellm_params:
    model: gretelai/gpt-mistral-nemo-2407
    api_key: os.environ/GRETEL_PROD_API_KEY
    api_base: https://api.gretel.ai
  tags:
  - open_license
  - nl
  - code